
##Create
POST http://localhost:8080/task/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiIxMjM4OTA3NjUxIiwic3ViIjoiMTIzODkwNzY1MSIsImlhdCI6MTc1NjgyNjQ4NSwiZXhwIjoxNzU2OTEyODg1fQ.wNeqBZT6ou_8euWWBkoaD-JBYp2uNtqf4AY3OcD5_52muIcwOhhJGgXdiGZ3uzeJuAujEo7z_44ALqFS-FYMlQ
#Authorization: Basic OTk4OTA3NjUxOjExMg==

{
  "title": "Jwt dan Samalyot Vertolyot",
  "content": "MAnipulyatsiyasi "
}


###Create Xolidning Basic
POST http://localhost:8080/task/create
Content-Type: application/json
Authorization: Basic OTk4OTA3NjUxOjExMg==

{
  "title": "Somsa xonada Somsa Pishiramiz",
  "content": "OLovni yoqmaiz "
}
###Create Aisha Basic
POST http://localhost:8080/task/create
Content-Type: application/json
Authorization: Basic OTkxMTAwMjIzMzoxMzEz

{
  "title": "Buxoro Samarqand",
  "content": "Hur Olimlar yo'li "
}



###3Update
PUT http://localhost:8080/task/28d33817-5ff0-4883-9579-e6b5209b8975
Content-Type: application/json
Authorization: Basic OTk4OTA3NjUxOjExMg==

{
  "title": "Amazon",
  "content": "Google borib internet olib kelish kerak."
}





###All
GET localhost:8080/task/all/By
Content-Type: application/json
Authorization: Basic dXNlcmFrYToxMTMy



###All
GET localhost:8080/task/all/ByTasks
Content-Type: application/json
Authorization: Basic OTk4OTA3NjUxOjExMg==


###get vy id
GET localhost:8080/task/92723bb1-be29-485b-8503-10eef596c385
Content-Type: application/json

###Delete
DELETE http://localhost:8080/task/admin-delete-s/28d33817-5ff0-4883-9579-e6b5209b8975
#Authorization: Basic OTk4OTA3NjUxOjExMg==

#Authorization: Basic MTIzODkwNzY1MTozMzMxMTI=  // BU user rolida turibdi Bilol

###Jwt
POST localhost:8080/task/jwt-create

###GEt jwt
GET localhost:8080/task/parse-jwt/eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoibWVudmFtZW4iLCJzdWIiOiJtZW52YW1lbiIsImlhdCI6MTc1Njc5MjIyNywiZXhwIjoxNzU2ODc4NjI3fQ.vr6D2BF8U0d2nIGF1gq1ZeVvmFWaRnnuAmiE2JxQYUCrKKAWw1CKcZyOwLqDoc3UNPXm8NFpLakO3pnGRM9eYg


//Endi JWT EXCEPTION lar
